spring.application.name=Ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=ledger_user
spring.datasource.password=ledger_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Kafka Consumer config
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ledger-worker-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer