spring.application.name=Ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=ledger_user
spring.datasource.password=ledger_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true